import { mkdir, readFile, writeFile, rename, stat, open, unlink, link } from 'node:fs/promises'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import type { LocalAsset, AssetKind, BoundaryResult, DownloadRequest } from '../shared/contracts'
const source='https://geo.datav.aliyun.com/areas_v3/bound/'
export class Downloads {
 private records:LocalAsset[]=[];private active=new Map<string,AbortController>();private transfers=new Map<string,Promise<void>>();private index?:BoundaryResult[];private queue=Promise.resolve()
 constructor(private directory:string,private fetcher:typeof fetch=fetch){}
 async initialize(){try{this.records=JSON.parse(await readFile(path.join(this.directory,'resources.json'),'utf8'));for(const r of this.records)if(r.status==='downloading'){r.status='failed';r.error='下载中断，请重新下载';await unlink(r.path+'.'+r.id+'.part').catch(()=>{})}}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}}
 private persist(){const data=JSON.stringify(this.records,null,2);this.queue=this.queue.catch(()=>{}).then(async()=>{await mkdir(this.directory,{recursive:true});const file=path.join(this.directory,'resources.json');await writeFile(file+'.tmp',data);await rename(file+'.tmp',file)});return this.queue}
 async list(){return Promise.all(this.records.map(async r=>{const copy={...r};if(r.status==='ready')try{const s=await stat(r.path);copy.size=s.isFile()?s.size:0;copy.exists=true;copy.isDirectory=s.isDirectory()}catch{copy.exists=false}return copy}))}
 async search(query:string){if(typeof query!=='string'||!query.trim()||query.length>80)throw new Error('请输入地名或行政区代码');if(!this.index){const response=await this.fetcher(source+'all.json',{signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('DataV 地名索引请求失败');const data=await response.json();if(!Array.isArray(data))throw new Error('DataV 索引格式无效');const rows=data.filter(r=>Number.isInteger(r.adcode)&&typeof r.name==='string');const names=new Map(rows.map(r=>[r.adcode,r]));this.index=rows.map(r=>{const ancestors:string[]=[];let parent=r.parent;for(let i=0;i<5&&parent;i++){const p=names.get(parent);if(!p)break;ancestors.unshift(p.name);parent=p.parent}return {adcode:r.adcode,name:r.name,level:r.level,ancestors:ancestors.join(' / ')}})}const q=query.trim();return this.index.filter(r=>r.name.includes(q)||String(r.adcode)===q).sort((a,b)=>Number(b.name===q)-Number(a.name===q)).slice(0,100)}
 async register(kind:AssetKind,file:string){this.validateKind(kind);if(!path.isAbsolute(file))throw new Error('请输入本地绝对路径');const s=await stat(file);if(!s.isFile()&&!s.isDirectory())throw new Error('资源必须是文件或目录');const canonical=path.resolve(file);const old=this.records.find(r=>r.path===canonical);if(old)return old.id;const r:LocalAsset={id:randomUUID(),kind,name:path.basename(file),path:canonical,size:s.size,received:s.size,status:'ready',createdAt:new Date().toISOString()};this.records.unshift(r);await this.persist();return r.id}
 private validateKind(kind:AssetKind){if(!['imagery','terrain','boundary','tileset','image','model'].includes(kind))throw new Error('资源类型无效')}
 async start(request:DownloadRequest){this.validateKind(request.kind);if(!path.isAbsolute(request.directory)||/[\0\r\n]/.test(request.directory))throw new Error('下载目录必须是绝对路径');let url=request.url;let filename=request.filename
 if(request.kind==='boundary'){const matches=await this.search(String(request.adcode));const region=matches.find(r=>r.adcode===request.adcode);if(!region)throw new Error('行政区代码无效');url=source+region.adcode+(request.children&&region.level!=='district'?'_full':'')+'.json';filename=region.name+'-'+region.adcode+(request.children&&region.level!=='district'?'-下级边界':'')+'.geojson'}
 const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol)||parsed.username||parsed.password)throw new Error('请输入 HTTP 或 HTTPS 文件直链');if(!filename||filename.length>180||/[<>:"/\\|?*\x00-\x1f]/.test(filename)||filename==='.'||filename==='..'||/[. ]$/.test(filename))throw new Error('文件名无效');await mkdir(request.directory,{recursive:true});const target=path.join(request.directory,filename);if(this.records.some(r=>r.status==='downloading'&&r.path===target))throw new Error('该文件正在下载，请勿重复提交');try{await stat(target);throw new Error('同名文件已存在，请修改文件名或目录')}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}
 const r:LocalAsset={id:randomUUID(),kind:request.kind,name:filename,path:target,url,received:0,size:0,status:'downloading',createdAt:new Date().toISOString()};const controller=new AbortController();this.active.set(r.id,controller);this.records.unshift(r);await this.persist();const transfer=this.transfer(r,controller);this.transfers.set(r.id,transfer);void transfer.finally(()=>this.transfers.delete(r.id)).catch(()=>{});return r.id}
 private async transfer(r:LocalAsset,controller:AbortController){const temporary=r.path+'.'+r.id+'.part';const timer=setTimeout(()=>controller.abort(),15*60*1000);try{const response=await this.fetcher(r.url!,{signal:controller.signal});if(!response.ok||!response.body)throw new Error('下载失败：HTTP '+response.status);r.size=Number(response.headers.get('content-length'))||0;const handle=await open(temporary,'wx');try{const reader=response.body.getReader();while(true){const {done,value:chunk}=await reader.read();if(done)break;if(controller.signal.aborted)throw new Error('下载已取消');await handle.writeFile(chunk);r.received+=chunk.length}}finally{await handle.close()}if(controller.signal.aborted)throw new Error('下载已取消');if(!r.received)throw new Error('下载文件为空');if(r.kind==='boundary'){const d=JSON.parse(await readFile(temporary,'utf8'));if(d.type!=='FeatureCollection'||!Array.isArray(d.features)||!d.features.length||!d.features.every((f:any)=>['Polygon','MultiPolygon'].includes(f.geometry?.type)))throw new Error('DataV 返回的边界数据无效')}await link(temporary,r.path);r.size=r.received;r.status='ready'}catch(e){r.status=controller.signal.aborted?'cancelled':'failed';r.error=String(e)}finally{clearTimeout(timer);await unlink(temporary).catch(()=>{});this.active.delete(r.id);await this.persist()}}
 async close(){for(const c of this.active.values())c.abort();await Promise.allSettled(this.transfers.values());await this.queue}
 async cancel(id:string){this.active.get(id)?.abort();await this.transfers.get(id)}
 async forget(id:string){if(this.active.has(id))throw new Error('请先取消下载');this.records=this.records.filter(r=>r.id!==id);await this.persist()}
}
