<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, nextTick, defineAsyncComponent } from 'vue'
import { Layers3, RadioTower, Workflow, Settings2, FolderOpen, Plus, Search, RefreshCw, Play, Square, ExternalLink, Copy, Trash2, ChevronRight, Check, CircleAlert, Box, Image, Mountain, Globe2, X, ArrowUpRight, Terminal, FileInput, HardDrive, Activity, Link, Pause, Clock, CheckCircle2 } from 'lucide-vue-next'
import { kindLabels, type Snapshot, type Publication, type ServiceKind, type Settings, type Inspection, type JobRequest, type Job } from '../shared/contracts'
const Preview=defineAsyncComponent(()=>import('./Preview.vue'))
import Resources from './Resources.vue'
import Jobs from './Jobs.vue'
import { api as managementAPI, desktop } from './api'
const api=managementAPI
const tab=ref<'services'|'process'|'jobs'|'settings'|'resources'>('services')
const snapshot=ref<Snapshot>();const search=ref('');const selected=ref('');const busy=ref(false);const error=ref('');const notice=ref('');const inspection=ref<Inspection>();const inspecting=ref(false)
const removalDialog=ref<HTMLDialogElement>();const pendingRemoval=ref<Publication>();const removalError=ref('');const advancedDialog=ref<HTMLDialogElement>();const serviceDialog=ref<HTMLDialogElement>();const previewDialog=ref<HTMLDialogElement>();const previewPublication=ref<Publication>();const dialogTitle=ref('登记资源目录')
const form=ref({id:undefined as string|undefined,name:'',directory:'',mount:'',kind:'imagery' as ServiceKind})
const settings=ref<Settings>();const settingsDirty=ref(false)
const request=ref<JobRequest>({kind:'imagery',input:'',output:'',minZoom:0,maxZoom:15,workers:2,sourceCrs:'',scale:false,verticalDatum:'unknown'})
const kinds=['imagery','terrain','tileset','model','image'] as ServiceKind[]
const publications=computed(()=>snapshot.value?.publications??[])
const filtered=computed(()=>publications.value.filter(p=>`${p.name} ${p.directory} ${p.mount}`.toLowerCase().includes(search.value.toLowerCase())))
const current=computed(()=>publications.value.find(p=>p.id===selected.value))
const available=computed(()=>publications.value.filter(p=>p.valid&&p.enabled).length)
const activeJobs=computed(()=>snapshot.value?.jobs.filter(j=>['running','queued'].includes(j.status)).length??0)
const taskEngine=computed(()=>snapshot.value?.engines.find(e=>e.id===(request.value.kind==='imagery'?'gdal':request.value.kind==='terrain'?'terrain':'osgb')))
const taskReady=computed(()=>taskEngine.value?.available && snapshot.value?.engines.find(e=>e.id==='python')?.available)
const base=computed(()=>snapshot.value?.server.addresses[1]??snapshot.value?.server.addresses[0]??'http://127.0.0.1:8088')
const serviceURL=(p:Publication)=>base.value+p.mount+(p.kind==='terrain'?'layer.json':p.kind==='tileset'?'tileset.json':p.kind==='imagery'?`{z}/{x}/{y}.${p.indexed[0]?.path.split('.').pop()??'png'}`:p.indexed[0]?.path??'')
const status=(p:Publication)=>!p.enabled?'已停用':!p.valid?'目录无效':!snapshot.value?.server.running?'待启动':'已发布'
const jobLabels:Record<string,string>={queued:'等待执行',running:'处理中',succeeded:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断'}
const jobNames:Record<string,string>={imagery:'影像切片',terrain:'地形切片',osgb:'OSGB 转 3D Tiles'}
const icons={imagery:Image,terrain:Mountain,tileset:Layers3,model:Box,image:Image}
const bytes=(n:number)=>n>=1e9?(n/1e9).toFixed(2)+' GB':n>=1e6?(n/1e6).toFixed(1)+' MB':n>=1e3?(n/1e3).toFixed(1)+' KB':n+' B'
const time=(date:string)=>new Date(date).toLocaleString('zh-CN',{hour12:false})
let interval:ReturnType<typeof setInterval>;let polling=false;let restoreFocus:HTMLElement|null=null
async function poll(){if(polling)return;polling=true;try{snapshot.value=await api.snapshot();if(!settingsDirty.value)settings.value={...snapshot.value.settings}}catch(e){error.value=String(e)}finally{polling=false}}
async function action(fn:()=>Promise<unknown>,message=''){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn();await poll();notice.value=message}catch(e){error.value=String(e).replace(/^Error: /,'')}finally{busy.value=false}}
async function choose(target:'directory'|'input'|'output'){const mode=target==='input'&&request.value.kind!=='osgb'?'file':'directory';const filename=await api.choose(mode);if(!filename)return;if(target==='directory'){form.value.directory=filename;if(!form.value.name)form.value.name=filename.split(/[\\/]/).pop()??''}else{request.value[target]=filename;if(target==='input')await inspect()}}
async function inspect(){if(!request.value.input)return;inspection.value=undefined;inspecting.value=true;try{inspection.value=await api.inspect(request.value.input)}catch(e){error.value=String(e)}finally{inspecting.value=false}}
async function openService(p?:Publication){form.value=p?{id:p.id,name:p.name,directory:p.directory,mount:p.mount,kind:p.kind}:{id:undefined,name:'',directory:'',mount:'',kind:'imagery'};dialogTitle.value=p?'编辑目录映射':'登记资源目录';restoreFocus=document.activeElement as HTMLElement;serviceDialog.value?.showModal();await nextTick();serviceDialog.value?.querySelector('input')?.focus()}
function closeDialog(dialog?:HTMLDialogElement){dialog?.close();restoreFocus?.focus()}
async function saveService(){await action(async()=>{await api.savePublication({...form.value});closeDialog(serviceDialog.value)},'目录映射已保存')}
async function openRemoval(p:Publication){pendingRemoval.value=p;removalError.value='';restoreFocus=document.activeElement as HTMLElement;removalDialog.value?.showModal();await nextTick();removalDialog.value?.querySelector<HTMLButtonElement>('[data-cancel]')?.focus()}
function finishRemoval(){pendingRemoval.value=undefined;if(restoreFocus?.isConnected)restoreFocus.focus();else document.querySelector<HTMLButtonElement>('.page-heading .primary')?.focus()}
async function confirmRemoval(){if(busy.value||!pendingRemoval.value)return;busy.value=true;removalError.value='';const id=pendingRemoval.value.id;try{await api.removePublication(id);if(selected.value===id)selected.value='';closeDialog(removalDialog.value);await poll();notice.value='已移除映射配置，磁盘文件保留'}catch(e){removalError.value=String(e).replace(/^Error: /,'')}finally{busy.value=false}}
async function openPreview(p:Publication){if(!p.valid||!p.enabled||!snapshot.value?.server.running){error.value='请先保证目录有效，并启动发布服务';return}restoreFocus=document.activeElement as HTMLElement;previewPublication.value=p;previewDialog.value?.showModal()}
async function publishJob(job:Job){await openService();form.value={id:undefined,name:job.request.output.split(/[\\/]/).pop()??'加工成果',directory:job.request.output,mount:`/${job.request.kind==='osgb'?'tilesets':job.request.kind}/${job.id.slice(0,8)}/`,kind:job.request.kind==='osgb'?'tileset':job.request.kind}}
async function saveSettings(){if(!settings.value)return;await action(async()=>{await api.saveSettings({...settings.value!});settingsDirty.value=false},'设置已保存')}
async function selectEngine(key:'nginx'|'python'|'gdal'|'terrain'|'osgb'){const file=await api.choose('executable');if(file&&settings.value){settings.value[key]=file;settingsDirty.value=true}}
async function submit(){await action(async()=>{await api.submit({...request.value,longitude:typeof request.value.longitude==='number'?request.value.longitude:undefined,latitude:typeof request.value.latitude==='number'?request.value.latitude:undefined});tab.value='jobs'},'加工任务已提交')}
function sample(p:Publication){const url=base.value+p.mount;if(p.kind==='terrain')return `const terrain = await Cesium.CesiumTerrainProvider.fromUrl(${JSON.stringify(url)});\nviewer.terrainProvider = terrain;`;if(p.kind==='tileset')return `const tileset = await Cesium.Cesium3DTileset.fromUrl(${JSON.stringify(url+'tileset.json')});\nviewer.scene.primitives.add(tileset);\nawait viewer.zoomTo(tileset);`;if(p.kind==='imagery')return `viewer.imageryLayers.addImageryProvider(\n  new Cesium.UrlTemplateImageryProvider({\n    url: ${JSON.stringify(serviceURL(p))},\n    minimumLevel: ${p.minZoom??0},\n    maximumLevel: ${p.maxZoom??18}\n  })\n);`;if(p.kind==='model')return `viewer.entities.add({\n  position: Cesium.Cartesian3.fromDegrees(longitude, latitude, height),\n  model: { uri: ${JSON.stringify(serviceURL(p))} }\n});`;return serviceURL(p)}
onMounted(async()=>{await poll();interval=setInterval(()=>void poll(),2500)})
onBeforeUnmount(()=>clearInterval(interval))
</script>

<template>
 <div class="app-shell">
  <aside class="sidebar">
   <div class="brand"><img class="brand-mark" src="/logo.svg" alt="GIS Data Press Logo"/><div>GIS Data Press<small>数据加工与目录发布</small></div><button v-if="desktop" class="browser-button" aria-label="在默认浏览器打开管理界面" title="在默认浏览器打开管理界面" @click="action(()=>api.openBrowser())"><ExternalLink :size="16"/></button></div>
   <div class="workspace-label">工作空间 <span>LOCAL</span></div>
   <nav aria-label="主导航">
    <button :class="{active:tab==='services'}" @click="tab='services'"><RadioTower :size="19" />服务发布<span class="nav-count">{{publications.length}}</span></button>
    <button :class="{active:tab==='resources'}" @click="tab='resources'"><HardDrive :size="19"/>资源下载</button>
    <button :class="{active:tab==='process'}" @click="tab='process'"><Workflow :size="19" />数据处理</button>
    <button :class="{active:tab==='jobs'}" @click="tab='jobs'"><Clock :size="19" />任务中心<span v-if="activeJobs" class="nav-count">{{activeJobs}}</span></button>
    <button :class="{active:tab==='settings'}" @click="tab='settings'"><Settings2 :size="19" />引擎与设置</button>
   </nav>
   <div class="sidebar-bottom"><span class="dot" :class="{online:snapshot?.server.running}"></span>{{snapshot?.server.running?'Nginx 正在运行':'发布服务未启动'}}<small>v0.1.0 · Desktop Edition</small></div>
  </aside>
  <main :class="{'process-workspace':tab==='process'}">
   <header class="topbar"><div class="breadcrumb">工作空间 <ChevronRight :size="14"/> {{tab==='resources'?'资源下载':tab==='services'?'服务发布':tab==='process'?'数据处理':tab==='jobs'?'任务中心':'引擎与设置'}}</div><span class="local-tag"><span class="dot online"></span>本地工作环境</span></header>
   <div class="content">
    <div v-if="error" class="alert error" role="alert"><CircleAlert :size="18"/><span>{{error}}</span><button aria-label="关闭错误提示" @click="error=''"><X :size="16"/></button></div>
    <div v-if="notice" class="alert success" role="status"><Check :size="18"/><span>{{notice}}</span><button aria-label="关闭操作提示" @click="notice=''"><X :size="16"/></button></div>
    <Resources v-if="tab==='resources'" @process="(kind,path)=>{request.kind=kind;request.input=path;inspection=undefined;tab='process'}" @publish="async(kind,path)=>{await openService();form.kind=kind as ServiceKind;form.directory=path;form.name=path.split(/[\\/]/).pop()||'本地资源'}"/>
    <template v-if="tab==='services'">
     <div class="page-heading"><div><div class="eyebrow">PUBLISH YOUR DATA</div><h1>服务发布</h1><p>将本地资源目录发布为地图可直接访问的静态服务。</p></div><button class="primary" @click="openService()"><Plus :size="17"/>登记资源目录</button></div>
     <div class="metrics">
      <div class="metric"><div><span>已登记目录</span><strong>{{publications.length.toString().padStart(2,'0')}}</strong><small>影像、地形、模型与图片</small></div><FolderOpen :size="24"/></div>
      <div class="metric"><div><span>有效映射</span><strong>{{available.toString().padStart(2,'0')}}</strong><small>目录存在且资源检查通过</small></div><CheckCircle2 :size="24"/></div>
      <div class="metric server-metric"><div><span>发布引擎</span><strong class="engine-name">Nginx <i :class="{online:snapshot?.server.running}">{{snapshot?.server.running?'运行中':'已停止'}}</i></strong><small>{{base}} · {{snapshot?.settings.host==='0.0.0.0'?'内网可访问':'仅本机访问'}}</small></div><button class="engine-button" :disabled="busy" @click="action(()=>api.server(snapshot?.server.running?'stop':'start'),snapshot?.server.running?'发布服务已停止':'发布服务已启动')"><Square v-if="snapshot?.server.running" :size="14"/><Play v-else :size="14"/>{{snapshot?.server.running?'停止':'启动'}}</button></div>
     </div>
     <div v-if="snapshot?.server.error" class="alert error" role="alert">{{snapshot.server.error}}</div>
     <section class="panel">
      <div class="panel-toolbar"><div class="section-title">目录映射 <span>{{publications.length}}</span></div><div class="toolbar-actions"><label class="search"><Search :size="16"/><input v-model="search" aria-label="搜索服务名称或目录" placeholder="搜索名称、路径…"/></label><button class="ghost" :disabled="busy" @click="action(()=>api.refresh(),'目录状态已更新')"><RefreshCw :size="16"/>检查目录</button></div></div>
      <table v-if="filtered.length" class="service-table"><thead><tr><th>服务 / 资源目录</th><th>类型</th><th>状态</th><th>资源数</th><th>操作</th></tr></thead><tbody><tr v-for="p in filtered" :key="p.id" :class="{selected:selected===p.id}"><td><button class="service-name" @click="selected=selected===p.id?'':p.id"><span class="resource-icon" :class="p.kind"><component :is="icons[p.kind]" :size="20"/></span><span><strong>{{p.name}}</strong><small :title="p.directory">{{p.directory}}</small></span></button></td><td>{{kindLabels[p.kind]}}</td><td><span class="badge" :class="!p.valid&&p.enabled?'invalid':p.valid&&p.enabled&&snapshot?.server.running?'valid':'idle'">{{status(p)}}</span></td><td class="mono">{{p.count.toLocaleString()}}</td><td><div class="row-actions"><button class="icon-button" :aria-label="'预览 '+p.name" :disabled="!p.valid||!p.enabled||!snapshot?.server.running" @click="openPreview(p)"><Globe2 :size="17"/></button><button class="icon-button" :aria-label="'复制 '+p.name+' 服务地址'" @click="action(()=>api.copy(serviceURL(p)),'服务地址已复制')"><Copy :size="16"/></button><button class="icon-button" :aria-label="(p.enabled?'停用 ':'启用 ')+p.name" :disabled="busy" @click="action(()=>api.togglePublication(p.id))"><Pause v-if="p.enabled" :size="16"/><Play v-else :size="16"/></button><button class="icon-button danger" :aria-label="'移除 '+p.name+' 的映射配置'" :disabled="busy" @click="openRemoval(p)"><Trash2 :size="16"/></button></div></td></tr></tbody></table>
      <div v-else class="empty-state"><div class="empty-art"><FolderOpen :size="36"/><span><Plus :size="14"/></span></div><h2>{{search?'没有匹配的目录':'发布你的第一个资源目录'}}</h2><p>选择已有瓦片、模型或图片目录，生成服务地址。<br>目录中的文件由 Nginx 直接提供给客户端。</p><button v-if="!search" class="primary" @click="openService()"><Plus :size="16"/>登记资源目录</button></div>
      <div class="panel-foot"><Activity :size="14"/>目录变化自动检查，另每 30 秒复查。资源失效时禁用映射。<span>索引不复制文件</span></div>
     </section>
     <section v-if="current" class="panel detail-panel"><div class="panel-toolbar"><div class="section-title">{{current.name}} <span>目录详情</span></div><button class="ghost" @click="openService(current)"><Settings2 :size="15"/>编辑映射</button></div><div class="detail-grid"><div><label>URL 前缀</label><code>{{current.mount}}</code><label>检查结果</label><p :class="{'text-error':!current.valid}">{{current.reason}}</p><label>最近检查</label><p>{{time(current.indexedAt)}}</p><button class="ghost" @click="action(()=>api.reveal(current!.directory))"><FolderOpen :size="16"/>打开本地目录</button></div><div><div class="code-head">Cesium 接入 <button class="ghost" @click="action(()=>api.copy(sample(current!)),'接入示例已复制')"><Copy :size="14"/>复制</button></div><pre>{{sample(current)}}</pre></div></div><details class="resource-list"><summary>资源索引 · 显示前 {{current.indexed.length}} 项</summary><div v-for="r in current.indexed" :key="r.path"><code>{{r.path}}</code><span>{{bytes(r.size)}}</span></div></details></section>
     <div class="guide-grid"><div><span class="guide-number">01</span><strong>选择资源目录</strong><p>支持已有 XYZ、Quantized Mesh、<br>3D Tiles、模型和图片文件。</p></div><div><span class="guide-number">02</span><strong>配置发布映射</strong><p>设置 URL 前缀与监听端口，<br>软件自动检查资源有效性。</p></div><div><span class="guide-number">03</span><strong>连接你的地图</strong><p>启动服务，复制 URL 或接入代码，<br>在 Cesium 中加载本地资源。</p></div></div>
    </template>

    <template v-if="tab==='process'">
     <div class="page-heading"><div><h1>数据处理</h1><p>读取本地数据，将加工成果输出到你指定的空目录。</p></div><span class="outline-tag">成果写入本地目录</span></div>
     <div class="processing-layout"><form class="panel processing-form" @submit.prevent="submit">
      <div class="section-title">新建加工任务 <span>01 选择数据 · 02 配置参数 · 03 提交</span></div><fieldset class="kind-picker"><legend>处理类型</legend><label v-for="kind in (['imagery','terrain','osgb'] as const)" :key="kind" :class="{chosen:request.kind===kind}"><input v-model="request.kind" type="radio" :value="kind" @change="inspection=undefined;request.input='';request.maxZoom=request.kind==='terrain'?14:15"/><Image v-if="kind==='imagery'" :size="20"/><Mountain v-else-if="kind==='terrain'" :size="20"/><Layers3 v-else :size="20"/><strong>{{jobNames[kind]}}</strong><small>{{kind==='imagery'?'GeoTIFF → XYZ':kind==='terrain'?'DEM → Quantized Mesh':'OSGB → 3D Tiles'}}</small></label></fieldset>
      <label for="input-path">{{request.kind==='osgb'?'输入 OSGB 完整目录':'输入 TIFF / VRT 文件'}}</label><div class="path-input"><input id="input-path" v-model="request.input" required placeholder="选择或输入本地绝对路径" @change="inspection=undefined"/><button type="button" class="ghost" @click="action(()=>choose('input'))"><FolderOpen :size="16"/>选择</button></div>
      <label for="output-path">输出目录</label><div class="path-input"><input id="output-path" aria-describedby="output-help" v-model="request.output" required placeholder="选择一个空目录，或输入新的目录路径"/><button type="button" class="ghost" @click="action(()=>choose('output'))"><FolderOpen :size="16"/>选择</button></div><small id="output-help" class="field-help">使用空目录，不能与已发布目录重叠。</small>
      <div v-if="request.kind!=='osgb'" class="process-parameters"><div><label for="min-zoom">最小层级</label><input id="min-zoom" v-model.number="request.minZoom" type="number" min="0" max="22" required/></div><div><label for="max-zoom">最大层级</label><input id="max-zoom" v-model.number="request.maxZoom" type="number" :min="request.minZoom" max="22" required/></div><button type="button" class="ghost advanced-trigger" @click="restoreFocus=$event.currentTarget as HTMLElement;advancedDialog?.showModal()"><Settings2 :size="15"/>高级参数</button></div>
      <p v-if="inspection?.recommendedZoom&&request.kind!=='osgb'" class="zoom-recommendation"><span>源分辨率建议最大 {{inspection.recommendedZoom[request.kind]}} 级{{request.maxZoom>inspection.recommendedZoom[request.kind]?' · 当前层级可能过度采样':''}}</span><button type="button" class="text-button" @click="request.maxZoom=inspection!.recommendedZoom![request.kind as 'imagery'|'terrain']">使用建议</button></p>
      <p v-if="request.kind!=='osgb'" class="parameter-summary">{{request.workers}} 个请求并行 · {{request.sourceCrs||'自动读取坐标系'}}<span v-if="request.kind==='imagery'&&request.scale"> · 百分位拉伸</span></p>
      <div v-if="request.kind==='terrain'"><label for="vertical-datum">DEM 高程基准</label><select id="vertical-datum" v-model="request.verticalDatum"><option value="unknown">尚未确认</option><option value="ellipsoid">已确认是米制 WGS84 椭球高</option></select><small class="field-help">仅支持米制 WGS84 椭球高；其他高程基准请先转换。</small></div>
      <div v-if="request.kind==='osgb'" class="form-grid"><div><label for="longitude">定位经度（可选）</label><input id="longitude" v-model.number="request.longitude" type="number" step="any" min="-180" max="180" placeholder="metadata.xml 缺失时填写"/></div><div><label for="latitude">定位纬度（可选）</label><input id="latitude" v-model.number="request.latitude" type="number" step="any" min="-90" max="90" placeholder="WGS84 纬度"/></div></div>
      <div class="process-actions"><div class="engine-hint" :class="{missing:!taskReady}"><span class="dot" :class="{online:taskReady}"></span><span>{{taskReady?taskEngine?.label+' 已就绪':'转换引擎未就绪'}}</span><button v-if="!taskReady" type="button" class="text-button" @click="tab='settings'">配置引擎 <ArrowUpRight :size="14"/></button></div><button class="primary" :disabled="busy||!taskReady||(request.kind==='terrain'&&request.verticalDatum!=='ellipsoid')"><Play :size="16"/>提交加工任务</button><small v-if="request.kind==='terrain'&&request.verticalDatum!=='ellipsoid'" class="submission-help">确认高程基准后才能提交地形任务。</small></div>
     </form><aside class="panel inspection-panel"><div class="section-title"><FileInput :size="18"/>输入数据检查</div><button class="ghost wide" :disabled="!request.input||inspecting" @click="action(()=>inspect())"><Search :size="16"/>{{inspecting?'正在读取…':'读取数据元信息'}}</button><div v-if="inspection" class="inspection-info"><dl><template v-for="(value,key) in {类型:inspection.type,文件大小:inspection.size?bytes(inspection.size):undefined,栅格尺寸:inspection.width?inspection.width+' × '+inspection.height:undefined,波段:inspection.bands,坐标系:inspection.crs,数据类型:inspection.dtype,高程单位:inspection.bands===1?(inspection.units||'未声明'):undefined,无效值:inspection.nodata,OSGB文件:inspection.files}" :key="key"><dt v-if="value!==undefined">{{key}}</dt><dd v-if="value!==undefined">{{value??'未设置'}}</dd></template></dl><label v-if="inspection.bounds">范围</label><code v-if="inspection.bounds">{{inspection.bounds.map(n=>n.toFixed(5)).join(', ')}}</code><p v-for="warning in inspection.warnings" :key="warning" class="inspection-warning"><CircleAlert :size="15"/>{{warning}}</p></div><div v-else class="inspection-empty"><FileInput :size="38"/><p>选择文件后读取尺寸、<br>坐标系、波段和覆盖范围。</p></div><div class="inspection-note"><strong>处理与发布独立</strong><p>完成加工后，在任务中心登记输出目录，即可发布为静态服务。</p></div></aside></div>
    </template>

    <Jobs v-if="tab==='jobs'" :jobs="snapshot?.jobs??[]" :settings="snapshot?.settings" :busy="busy" @create="tab='process'" @settings="tab='settings'" @cancel="id=>action(()=>api.cancel(id))" @reveal="path=>action(()=>api.reveal(path))" @publish="publishJob" @retry="async job=>{request={...job.request};inspection=undefined;tab='process';await inspect()}"/>

    <template v-if="tab==='settings' && settings">
     <div class="page-heading"><div><div class="eyebrow">RUNTIME & NETWORK</div><h1>引擎与设置</h1><p>配置本地引擎和静态服务监听方式。</p></div><button class="primary" :disabled="busy" @click="saveSettings"><Check :size="16"/>保存设置</button></div>
     <section class="panel settings-panel"><div class="section-title">服务网络</div><div class="form-grid"><div><label for="port">监听端口</label><input id="port" v-model.number="settings.port" type="number" min="1024" max="65535" @input="settingsDirty=true"/></div><div><label for="host">访问范围</label><select id="host" v-model="settings.host" @change="settingsDirty=true"><option value="127.0.0.1">仅本机 · 127.0.0.1</option><option value="0.0.0.0">局域网 · 0.0.0.0</option></select></div><div><label for="cache">客户端缓存（秒）</label><input id="cache" v-model.number="settings.cacheSeconds" type="number" min="0" max="86400" @input="settingsDirty=true"/><small class="field-help">原地修改资源时建议设为 0；客户端已有缓存不会被目录监测清除。</small></div></div><div class="network-addresses"><span>访问地址</span><code v-for="address in snapshot?.server.addresses" :key="address">{{address}}</code></div><p class="field-help">修改监听地址或端口前请停止服务。关闭窗口只停止管理页面服务；GIS 发布与任务在后台继续运行。发布服务需在此明确停止。</p></section>
     <section class="panel settings-panel"><div class="section-title">任务并发</div><div class="form-grid"><div><label for="task-concurrency">同时运行任务数</label><input id="task-concurrency" v-model.number="settings.taskConcurrency" type="number" min="1" max="4" @input="settingsDirty=true"/></div><div><label for="worker-budget">总并行预算</label><input id="worker-budget" v-model.number="settings.workerBudget" type="number" min="1" max="16" @input="settingsDirty=true"/></div></div><p class="field-help">默认同时运行 2 个任务，总并行预算 4。每个任务使用空余预算内的并行数；预算用完后排队。降低设置不会打断正在运行的任务。</p></section>
     <section class="panel settings-panel"><div class="section-title">处理与发布引擎 <span>路径留空时自动查找</span></div><div v-for="engine in snapshot?.engines" :key="engine.id" class="engine-row"><div class="engine-label"><span class="dot" :class="{online:engine.available}"></span><strong>{{engine.label}}</strong><small>{{engine.available?'已找到':'未安装 / 未配置'}}</small></div><div class="path-input"><input :id="'engine-'+engine.id" v-model="settings[engine.id as 'nginx'|'python'|'gdal'|'terrain'|'osgb']" :aria-label="engine.label+' 可执行文件路径'" :placeholder="engine.path||'选择可执行文件，或填写命令名称'" @input="settingsDirty=true"/><button class="ghost" @click="action(()=>selectEngine(engine.id as 'nginx'|'python'|'gdal'|'terrain'|'osgb'))"><FolderOpen :size="15"/>选择</button></div></div><p class="field-help">地形需要支持 Mesh 的 CTB 分支，或已下载的 Docker CTB 镜像（路径填写 docker://ctb）；OSGB 需要 fanvanzh/3dtiles 兼容引擎。引擎存在不代表所有数据都兼容。</p></section>
     <section class="panel settings-panel"><div class="section-title">资源访问日志 <span>最近 80 条</span></div><pre class="log-output">{{snapshot?.logs.join('\n')||'暂无访问记录。启动服务并访问资源后显示日志。'}}</pre></section>
    </template>

   </div>
  </main>
 </div>
 <dialog ref="removalDialog" class="service-dialog removal-dialog" aria-labelledby="removal-title" aria-describedby="removal-description" @cancel="busy&&$event.preventDefault()" @close="finishRemoval"><div class="advanced-body"><div class="dialog-header"><h2 id="removal-title">确认移除服务映射？</h2><button type="button" class="icon-button" aria-label="关闭移除确认" :disabled="busy" @click="closeDialog(removalDialog)"><X :size="20"/></button></div><div class="removal-summary"><strong>{{pendingRemoval?.name}}</strong><code>{{pendingRemoval?.mount}}</code></div><p id="removal-description">移除后，该服务地址将不再提供资源。磁盘中的原始数据和加工成果会保留。</p><div v-if="removalError" class="alert error" role="alert">{{removalError}}</div><div class="dialog-footer"><button type="button" data-cancel class="ghost" :disabled="busy" @click="closeDialog(removalDialog)">取消</button><button type="button" class="primary destructive" :disabled="busy" @click="confirmRemoval"><Trash2 :size="15"/>{{busy?'正在移除…':'确认移除'}}</button></div></div></dialog>
 <dialog ref="advancedDialog" class="service-dialog advanced-dialog" aria-labelledby="advanced-title" @close="restoreFocus?.focus()"><div class="advanced-body"><div class="dialog-header"><div><h2 id="advanced-title">高级参数</h2><p>参数直接用于当前任务。</p></div><button type="button" class="icon-button" aria-label="关闭高级参数" @click="closeDialog(advancedDialog)"><X :size="20"/></button></div><div class="form-grid"><div><label for="workers">单任务并行数</label><input id="workers" v-model.number="request.workers" type="number" min="1" max="8" required/></div><div><label for="source-crs">源坐标系（可选）</label><input id="source-crs" v-model="request.sourceCrs" placeholder="例如 EPSG:4490"/></div></div><label v-if="request.kind==='imagery'" class="checkbox"><input v-model="request.scale" type="checkbox"/>按采样的 2%–98% 百分位拉伸至 RGB Byte</label><div class="dialog-footer"><button class="primary" @click="closeDialog(advancedDialog)"><Check :size="16"/>完成</button></div></div></dialog>
 <dialog ref="serviceDialog" class="service-dialog" aria-labelledby="service-dialog-title" @cancel="restoreFocus?.focus()"><form @submit.prevent="saveService"><div class="dialog-header"><div><h2 id="service-dialog-title">{{dialogTitle}}</h2><p>将 URL 前缀映射到一个本地资源目录。</p></div><button type="button" class="icon-button" aria-label="关闭目录映射窗口" @click="closeDialog(serviceDialog)"><X :size="20"/></button></div><label for="service-name">服务名称</label><input id="service-name" v-model="form.name" maxlength="80" required placeholder="例如：中国 30 米地形"/><label for="service-kind">资源类型</label><select id="service-kind" v-model="form.kind"><option v-for="kind in kinds" :key="kind" :value="kind">{{kindLabels[kind]}}</option></select><label for="service-directory">本地资源目录</label><div class="path-input"><input id="service-directory" v-model="form.directory" required placeholder="选择资源所在目录"/><button type="button" class="ghost" @click="action(()=>choose('directory'))"><FolderOpen :size="16"/>选择</button></div><label for="service-mount">URL 前缀</label><input id="service-mount" v-model="form.mount" required placeholder="例如 /terrain/china/" aria-describedby="mount-help"/><small id="mount-help" class="field-help">只允许英文、数字、下划线、短横线和分层斜线。</small><div v-if="error" class="alert error" role="alert">{{error}}</div><div class="dialog-footer"><button type="button" class="ghost" @click="closeDialog(serviceDialog)">取消</button><button class="primary" :disabled="busy"><RadioTower :size="16"/>保存目录映射</button></div></form></dialog>
 <dialog ref="previewDialog" class="preview-dialog" aria-labelledby="preview-dialog-title" @close="previewPublication=undefined;restoreFocus?.focus()"><div class="dialog-header"><div><h2 id="preview-dialog-title">{{previewPublication?.name}}</h2><p>直接加载当前 Nginx 服务中的资源</p></div><button class="icon-button" aria-label="关闭资源预览" @click="closeDialog(previewDialog)"><X :size="20"/></button></div><Preview v-if="previewPublication" :key="previewPublication.id" :publication="previewPublication" :base="base"/></dialog>
</template>
